export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const CREATE_TUTORIAL  ="CREATE_TUTORIAL";
export const UPDATE_TUTORIAL ="UPDATE_TUTORIAL"
export const DELETE_TUTORIAL = "DELETE_TUTORIAL"
export const SEARCH_FOR_TITLE ="SEARCH_FOR_TITLE"